import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from './supabase-config.js';

const configured = SUPABASE_URL && SUPABASE_ANON_KEY && !SUPABASE_URL.startsWith('__');
const supabase = configured ? createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
const root = document.querySelector('#root');
const state = { user:null, profile:null, rooms:[], bookings:[], events:[], notifications:[], settings:null, page:'dashboard', authMode:'login', bookingFilter:'all', search:'', realtime:null };
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=d=>d?new Date(`${d}T00:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—';
const fmtDT=d=>d?new Date(d).toLocaleString():'—';
const getUiPrefs=()=>{try{return JSON.parse(localStorage.getItem('vmc_ui_prefs')||'{}')}catch{return {}}};
const uiPrefs=()=>Object.assign({theme:'light',fontSize:'default',density:'comfortable',design:'modern'},getUiPrefs());
const applyUiPrefs=()=>{const p=uiPrefs();document.documentElement.dataset.theme=p.theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):p.theme;document.documentElement.dataset.fontSize=p.fontSize;document.documentElement.dataset.density=p.density;document.documentElement.dataset.design=p.design;const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=p.theme==='dark'?'#0b1020':'#f6f8fb'};
const saveUiPrefs=patch=>{const next={...uiPrefs(),...patch};localStorage.setItem('vmc_ui_prefs',JSON.stringify(next));applyUiPrefs();return next};
applyUiPrefs();
window.addEventListener('storage',e=>{if(e.key==='vmc_ui_prefs'){applyUiPrefs();if(state.user)renderApp()}});
if(window.matchMedia)window.matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(uiPrefs().theme==='system')applyUiPrefs()});
const isAdmin=()=>state.profile?.role==='admin';
const defaultPermissions={student:{view_rooms:true,book_rooms:true,manage_own_bookings:true,calendar:true,profile:true,notifications:true},teacher:{view_rooms:true,book_rooms:true,manage_own_bookings:true,calendar:true,profile:true,notifications:true}};
const permissions=()=>state.settings?.permissions||defaultPermissions;
const can=(key)=>isAdmin() || Boolean(permissions()[state.profile?.role]?.[key]);
const brand=()=>({name:state.settings?.app_name||'VMC Scheduler',tagline:state.settings?.tagline||'Classroom Scheduling & Facility Booking',logo:state.settings?.logo_url||''});
const stopRealtime=()=>{if(state.realtime){supabase.removeChannel(state.realtime);state.realtime=null}};
const safeAction=async(btn,fn)=>{if(!btn)return;const old=btn.textContent;btn.disabled=true;btn.setAttribute('aria-busy','true');try{await fn()}catch(e){fail(e)}finally{btn.disabled=false;btn.removeAttribute('aria-busy');btn.textContent=old}};
function startRealtime(){stopRealtime();if(!state.user)return;state.realtime=supabase.channel(`vmc-live-${state.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'app_settings'},async()=>{await loadData();render()}).on('postgres_changes',{event:'*',schema:'public',table:'rooms'},async()=>{await refresh('rooms');if(state.page==='facilities'||state.page==='available')renderApp()}).on('postgres_changes',{event:'*',schema:'public',table:'bookings'},async()=>{await loadData();if(state.page==='bookings'||state.page==='dashboard')renderApp()}).on('postgres_changes',{event:'*',schema:'public',table:'events'},async()=>{await loadData();if(state.page==='calendar'||state.page==='dashboard')renderApp()}).on('postgres_changes',{event:'*',schema:'public',table:'profiles'},async()=>{await loadData();render()}).on('postgres_changes',{event:'*',schema:'public',table:'notifications'},async()=>{await loadData();if(state.page==='notifications'||state.page==='dashboard')renderApp()}).subscribe()}
const statusLabel=s=>({pending:'Pending',approved:'Approved',rejected:'Rejected',cancelled:'Cancelled'}[s]||s);
const fail=e=>{console.error(e); alert(e?.message||String(e));};

function configurationScreen(){root.innerHTML=`<div class="auth-page"><div class="auth-card"><div class="brand-block"><div class="brand-mark">VMC</div><div><h1>VMC Scheduler</h1><p>Supabase setup required</p></div></div><div class="alert error">Supabase is not configured yet.</div><p>For local use, replace the placeholders in <strong>supabase-config.js</strong>. For Cloudflare Pages, set <strong>SUPABASE_URL</strong> and <strong>SUPABASE_ANON_KEY</strong> as build environment variables, then deploy.</p><p>Run <strong>supabase.sql</strong> once in Supabase SQL Editor first.</p></div></div>`}

async function boot(){
 if(!configured){configurationScreen();return}
 const {data:{session}}=await supabase.auth.getSession();
 state.user=session?.user||null;
 if(state.user){await loadData();startRealtime()}
 render();
 supabase.auth.onAuthStateChange((_event,session)=>{setTimeout(async()=>{state.user=session?.user||null;if(state.user){try{await loadData();startRealtime()}catch(e){fail(e)}}else{stopRealtime();resetData()}render()},0)});
}
function resetData(){Object.assign(state,{profile:null,rooms:[],bookings:[],events:[],notifications:[],settings:null,page:'dashboard'})}

async function loadData(){
 const uid=state.user.id;
 const [p,r,b,e,n,s]=await Promise.all([
   supabase.from('profiles').select('*').eq('id',uid).single(),
   supabase.from('rooms').select('*').order('name'),
   supabase.from('bookings').select('*, rooms(name,capacity,room_code,location,image_url), profiles(name,email,role)').order('created_at',{ascending:false}),
   supabase.from('events').select('*, profiles(name)').order('event_date'),
   supabase.from('notifications').select('*').order('created_at',{ascending:false}),
   supabase.from('app_settings').select('*').eq('id',1).single()
 ]);
 for(const x of [p,r,b,e,n,s]) if(x.error) console.warn(x.error);
 state.profile=p.data||null; state.rooms=r.data||[]; state.bookings=b.data||[]; state.events=e.data||[]; state.notifications=n.data||[]; state.settings=s.data||{id:1,app_name:'VMC Scheduler',tagline:'Classroom Scheduling & Facility Booking',logo_url:'',open_days:[1,2,3,4,5],open_time:'07:00:00',close_time:'18:00:00',permissions:defaultPermissions}; if(!state.settings.permissions)state.settings.permissions=defaultPermissions;
}
async function refresh(section='all'){if(section==='all')return loadData();if(section==='rooms'){const{data,error}=await supabase.from('rooms').select('*').order('name');if(error)throw error;state.rooms=data||[]}}

function render(){applyUiPrefs();if(!state.user)return renderAuth();renderApp()}
function renderAuth(){const b=brand();root.innerHTML=`<div class="auth-page"><div class="ambient a1"></div><div class="ambient a2"></div><div class="auth-card"><div class="brand-block">${b.logo?`<img class="brand-logo" src="${esc(b.logo)}" alt="${esc(b.name)}">`:`<div class="brand-mark">VMC</div>`}<div><h1>${esc(b.name)}</h1><p>${esc(b.tagline)}</p></div></div><div class="auth-tabs"><button data-mode="login" class="${state.authMode==='login'?'active':''}">Login</button><button data-mode="signup" class="${state.authMode==='signup'?'active':''}">Create Account</button></div>${state.authMode==='login'?`<form id="authForm"><label>Email<input name="email" type="email" required autocomplete="email"></label><label>Password<input name="password" type="password" required autocomplete="current-password"></label><div id="authMsg"></div><button class="primary full">Sign in</button></form>`:`<form id="authForm"><label>Full name<input name="name" required></label><label>Email<input name="email" type="email" required autocomplete="email"></label><div class="two"><label>Role<select name="role"><option value="student">Student</option><option value="teacher">Teacher</option></select></label><label>ID number<input name="id_number"></label></div><label>Department / Section<input name="department"></label><label>Password<input name="password" type="password" minlength="6" required autocomplete="new-password"></label><div id="authMsg"></div><button class="primary full">Create Account</button></form>`}<div class="demo-note">Accounts and sessions are secured by Supabase Auth.</div></div></div>`;
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.authMode=b.dataset.mode;renderAuth()});
 document.querySelector('#authForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),msg=document.querySelector('#authMsg');msg.innerHTML='';try{if(state.authMode==='login'){const{error}=await supabase.auth.signInWithPassword({email:String(fd.get('email')).trim(),password:String(fd.get('password'))});if(error)throw error}else{const{data,error}=await supabase.auth.signUp({email:String(fd.get('email')).trim(),password:String(fd.get('password')),options:{emailRedirectTo:location.origin,data:{name:String(fd.get('name')).trim(),role:String(fd.get('role')),department:String(fd.get('department')||'').trim(),id_number:String(fd.get('id_number')||'').trim()}}});if(error)throw error;msg.innerHTML=`<div class="alert success">${data.session?'Account created.':'Account created. Check your email if email confirmation is enabled.'}</div>`}}catch(err){msg.innerHTML=`<div class="alert error">${esc(err.message)}</div>`}}
}

const navs=[['dashboard','Dashboard'],['available','Available Rooms'],['facilities','Room Facilities'],['bookings','Bookings'],['calendar','Calendar'],['notifications','Notifications'],['profile','Profile'],['users','Users'],['settings','Settings']];
function renderApp(){
 const b=brand();
 const visibleNavs=navs.filter(([k])=>isAdmin()||({available:'book_rooms',facilities:'view_rooms',bookings:'manage_own_bookings',calendar:'calendar',notifications:'notifications',profile:'profile',dashboard:null,settings:null}[k]?can(({available:'book_rooms',facilities:'view_rooms',bookings:'manage_own_bookings',calendar:'calendar',notifications:'notifications',profile:'profile'}[k])):true));
 if(!visibleNavs.some(x=>x[0]===state.page))state.page='dashboard';
 root.innerHTML=`<div class="app-shell"><aside><div class="side-brand">${b.logo?`<img class="brand-logo side-logo" src="${esc(b.logo)}" alt="${esc(b.name)}">`:`<div class="brand-mark small">VMC</div>`}<span>${esc(b.name)}</span></div><nav>${visibleNavs.map(([k,l])=>`<button data-page="${k}" class="${state.page===k?'active':''}"><span class="nav-dot"></span>${l}</button>`).join('')}</nav><div class="side-user"><div class="avatar">${esc((state.profile?.name||'U')[0].toUpperCase())}</div><div><strong>${esc(state.profile?.name||state.user.email)}</strong><span>${esc(state.profile?.role||'user')}</span></div></div><button class="logout" id="logout">Logout</button></aside><main><header><div><h2>${visibleNavs.find(x=>x[0]===state.page)?.[1]||'Dashboard'}</h2><p>${esc(b.tagline)}</p></div><span class="role-pill">${esc(state.profile?.role||'user')}</span></header><section id="page" class="page"></section></main></div>`;
 document.querySelectorAll('[data-page]').forEach(btn=>btn.onclick=()=>{state.page=btn.dataset.page;renderApp()});
 const logout=document.querySelector('#logout');
 logout.onclick=async()=>{await safeAction(logout,async()=>{const{error}=await supabase.auth.signOut({scope:'local'});if(error)throw error;resetData();state.authMode='login';render()})};
 ({dashboard,available,facilities,bookings,calendar,notifications,profile,settings,users}[state.page]||dashboard)();
}
function setPage(html){document.querySelector('#page').innerHTML=html}

function dashboard(){const upcoming=state.bookings.filter(b=>['pending','approved'].includes(b.status)&&b.booking_date>=new Date().toISOString().slice(0,10)).slice(0,5);setPage(`<div class="stats"><div class="stat-card"><span>Room Facilities</span><strong>${state.rooms.filter(r=>r.active).length}</strong></div><div class="stat-card"><span>Bookings</span><strong>${state.bookings.length}</strong></div><div class="stat-card"><span>Unread Notifications</span><strong>${state.notifications.filter(n=>!n.read).length}</strong></div></div><div class="panel"><h3>Welcome back, ${esc(state.profile?.name||'User')}</h3><p>${isAdmin()?'You have full system control.':'Use the features enabled for your account.'}</p><div class="quick-actions"><button class="primary" data-go="available">Book a facility</button><button data-go="calendar">Add calendar event</button><button data-go="notifications">Notifications</button></div></div><div class="panel upcoming-panel"><h3>Upcoming bookings</h3>${upcoming.length?`<div class="mini-list">${upcoming.map(b=>`<button class="mini-booking" data-detail="${b.id}"><span><strong>${esc(b.rooms?.name||'Room')}</strong><small>${fmtDate(b.booking_date)} · ${esc(b.start_time.slice(0,5))}–${esc(b.end_time.slice(0,5))}</small></span><span class="status ${b.status}">${statusLabel(b.status)}</span></button>`).join('')}</div>`:`<p>No upcoming bookings.</p>`}</div>`);document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{state.page=b.dataset.go;renderApp()});document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>bookingDetails(state.bookings.find(x=>x.id===b.dataset.detail)))}

function roomCard(r,bookable=true){const canBook=bookable&&r.active&&can('book_rooms');return `<div class="facility-card ${r.active?'':'room-unavailable'}"><div class="room-image-wrap">${r.image_url?`<img class="room-image" src="${esc(r.image_url)}" alt="${esc(r.name)}">`:`<div class="room-image-placeholder">🏫</div>`}</div><div class="availability-top"><h3>${esc(r.name)}</h3>${r.room_code?`<span class="room-code">${esc(r.room_code)}</span>`:''}</div><p><strong>Capacity:</strong> ${r.capacity}${r.location?` · ${esc(r.location)}`:''}</p>${r.active?'':'<div class="status rejected" style="margin:6px 0 0">Under maintenance / unavailable</div>'}${r.description?`<p class="room-description">${esc(r.description)}</p>`:''}${r.amenities?.length?`<div class="amenity-list">${r.amenities.map(a=>`<span>${esc(a)}</span>`).join('')}</div>`:''}<div class="card-actions">${canBook?`<button class="primary" data-book="${r.id}">Book</button>`:''}${isAdmin()?`<button data-edit-room="${r.id}">Edit</button><button class="danger" data-delete-room="${r.id}">Delete</button>`:''}</div></div>`}
function attachRoomActions(){document.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>bookingModal(state.rooms.find(r=>r.id===b.dataset.book)));document.querySelectorAll('[data-edit-room]').forEach(b=>b.onclick=()=>roomModal(state.rooms.find(r=>r.id===b.dataset.editRoom)));document.querySelectorAll('[data-delete-room]').forEach(b=>b.onclick=()=>deleteRoom(b.dataset.deleteRoom))}
function facilities(){setPage(`<div class="toolbar"><p>${isAdmin()?'Add, edit, archive, or remove rooms and their information.':'View room details and book available facilities.'}</p>${isAdmin()?`<button class="primary" id="addRoom">+ Add facility</button>`:''}</div>${state.rooms.length?`<div class="card-grid">${state.rooms.map(r=>roomCard(r,true)).join('')}</div>`:`<div class="empty"><p>No rooms yet.</p></div>`}`);if(isAdmin())document.querySelector('#addRoom').onclick=()=>roomModal();attachRoomActions()}
function available(){if(!can('book_rooms')){setPage('<div class="empty"><p>Room booking is currently disabled for your account.</p></div>');return}setPage(`<div class="panel availability-checker"><h3>Check Available Rooms</h3><p>Select date, time, and participant count before booking.</p><form id="availForm"><div class="availability-fields"><label>Date<input name="date" type="date" required></label><label>Start<input name="start" type="time" required></label><label>End<input name="end" type="time" required></label><label>Participants<input name="participants" type="number" min="1" value="1" required></label></div><button class="primary">Check availability</button></form></div><div id="availResults"><div class="empty"><p>Choose a schedule above to check room availability.</p></div></div>`);document.querySelector('#availForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),q={date:String(fd.get('date')),start:String(fd.get('start')),end:String(fd.get('end')),participants:Number(fd.get('participants'))},out=document.querySelector('#availResults');if(!q.date||!q.start||!q.end||q.start>=q.end){out.innerHTML='<div class="alert error">Please select a valid date and time range.</div>';return}out.innerHTML='<div class="empty"><p>Checking room availability…</p></div>';const checks=await Promise.all(state.rooms.filter(r=>r.active).map(async r=>{const{data,error}=await supabase.rpc('room_is_available',{p_room_id:r.id,p_date:q.date,p_start:q.start,p_end:q.end,p_participants:q.participants});return !error&&data?r:null}));const list=checks.filter(Boolean);out.innerHTML=list.length?`<div class="card-grid">${list.map(r=>roomCard(r,true)).join('')}</div>`:`<div class="empty"><p>No rooms match this schedule and participant count.</p></div>`;attachRoomActions()}}
function bookingConflict(d,r){if(!d.date||!d.start||!d.end||d.start>=d.end||d.participants<1||d.participants>r.capacity)return true;const day=new Date(`${d.date}T00:00:00`).getDay(),s=state.settings;if(s&&!s.open_days.includes(day))return true;if(s&&(d.start<s.open_time.slice(0,5)||d.end>s.close_time.slice(0,5)))return true;return state.bookings.some(b=>b.booking_date===d.date&&!['rejected','cancelled'].includes(b.status)&&((b.room_id===r.id)||(b.user_id===state.user.id))&&d.start<b.end_time.slice(0,5)&&d.end>b.start_time.slice(0,5))}

function modal(title,body){closeModal();document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modalBackdrop"><div class="modal"><div class="modal-head"><h3>${title}</h3><button id="modalClose">×</button></div>${body}</div></div>`);document.querySelector('#modalClose').onclick=closeModal;document.querySelector('#modalBackdrop').onmousedown=e=>{if(e.target===e.currentTarget)closeModal()}}
function closeModal(){document.querySelector('#modalBackdrop')?.remove()}
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});

function roomModal(existing=null){modal(existing?'Edit facility':'Add facility',`<form id="roomForm"><div class="two"><label>Facility name<input name="name" value="${esc(existing?.name||'')}" required></label><label>Room code<input name="room_code" value="${esc(existing?.room_code||'')}" placeholder="e.g. AVR-01"></label></div><div class="two"><label>Capacity<input name="capacity" type="number" min="1" value="${existing?.capacity||1}" required></label><label>Location<input name="location" value="${esc(existing?.location||'')}" placeholder="Building / floor"></label></div><label>Description<textarea name="description" placeholder="Describe the room, ideal use, equipment, etc.">${esc(existing?.description||'')}</textarea></label><label>Amenities<input name="amenities" value="${esc((existing?.amenities||[]).join(', '))}" placeholder="Projector, Aircon, Whiteboard"></label><label>Room picture<input name="image" type="file" accept="image/png,image/jpeg,image/webp"></label>${existing?.image_url?`<img class="room-form-preview" src="${esc(existing.image_url)}" alt="Current room photo">`:''}<label class="check"><input name="active" type="checkbox" ${existing?.active===false?'':'checked'}> <span>Room is active / bookable</span></label><div id="roomMsg"></div><button class="primary full">${existing?'Save changes':'Add facility'}</button></form>`);document.querySelector('#roomForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),msg=document.querySelector('#roomMsg');try{let image_url=existing?.image_url||'';const file=fd.get('image');if(file?.size){if(file.size>5*1024*1024)throw new Error('Room photo must be 5 MB or smaller.');const ext=file.name.split('.').pop().toLowerCase(),path=`${crypto.randomUUID()}.${ext}`;const{error:upErr}=await supabase.storage.from('room-images').upload(path,file,{upsert:false});if(upErr)throw upErr;image_url=supabase.storage.from('room-images').getPublicUrl(path).data.publicUrl}const payload={name:String(fd.get('name')).trim(),capacity:Number(fd.get('capacity')),room_code:String(fd.get('room_code')||'').trim(),location:String(fd.get('location')||'').trim(),description:String(fd.get('description')||'').trim(),amenities:String(fd.get('amenities')||'').split(',').map(x=>x.trim()).filter(Boolean),image_url,active:fd.has('active'),updated_at:new Date().toISOString()};const q=existing?supabase.from('rooms').update(payload).eq('id',existing.id):supabase.from('rooms').insert(payload);const{error}=await q;if(error)throw error;await loadData();closeModal();facilities()}catch(err){msg.innerHTML=`<div class="alert error">${esc(err.message)}</div>`}}}
async function deleteRoom(id){if(!confirm('Delete this facility? Existing bookings may prevent deletion. If it has booking history, it will be archived instead.'))return;const{error}=await supabase.from('rooms').delete().eq('id',id);if(error){const{error:archiveError}=await supabase.from('rooms').update({active:false}).eq('id',id);if(archiveError)return fail(error);alert('This room has existing records, so it was archived and marked unavailable instead.')}await loadData();facilities()}

function bookingModal(r){modal(`Book: ${esc(r.name)}`,`<div class="room-booking-summary">${r.image_url?`<img src="${esc(r.image_url)}" alt="${esc(r.name)}">`:''}<div><strong>${esc(r.name)}</strong><small>${esc(r.location||'')} · Capacity ${r.capacity}</small>${r.amenities?.length?`<small>${esc(r.amenities.join(' · '))}</small>`:''}</div></div><form id="bookForm"><label>Participants<input name="participants" type="number" min="1" max="${r.capacity}" value="1" required></label><label>Date<input name="date" type="date" required></label><div class="two"><label>Start time<input name="start" type="time" required></label><label>End time<input name="end" type="time" required></label></div><label>Purpose<textarea name="purpose" required></textarea></label><div id="bookMsg"></div><button class="primary full">Submit booking</button></form>`);document.querySelector('#bookForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),d={participants:Number(fd.get('participants')),date:String(fd.get('date')),start:String(fd.get('start')),end:String(fd.get('end')),purpose:String(fd.get('purpose')).trim()},msg=document.querySelector('#bookMsg');if(bookingConflict(d,r)){msg.innerHTML='<div class="alert error">This room or your schedule conflicts with another booking, school hours, capacity, or the selected time.</div>';return}const{error}=await supabase.from('bookings').insert({user_id:state.user.id,room_id:r.id,participants:d.participants,booking_date:d.date,start_time:d.start,end_time:d.end,purpose:d.purpose});if(error){msg.innerHTML=`<div class="alert error">${esc(error.message)}</div>`;return}await loadData();closeModal();state.page='bookings';renderApp()}}

function bookings(){const q=state.search.toLowerCase(),list=state.bookings.filter(b=>(state.bookingFilter==='all'||b.status===state.bookingFilter)&&(!q||`${b.rooms?.name||''} ${b.profiles?.name||''} ${b.purpose}`.toLowerCase().includes(q)));setPage(`<div class="booking-tools"><div class="segmented booking-filter">${['all','pending','approved','rejected','cancelled'].map(x=>`<button data-filter="${x}" class="${state.bookingFilter===x?'active':''}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div><input id="bookingSearch" class="search-input" placeholder="Search requester, room, or purpose" value="${esc(state.search)}"></div>${list.length?`<div class="table-wrap"><table><thead><tr><th>Facility</th>${isAdmin()?'<th>Requester</th>':''}<th>Date</th><th>Status</th><th></th></tr></thead><tbody>${list.map(b=>`<tr><td><strong>${esc(b.rooms?.name||'Room')}</strong><small>${esc(b.purpose)}</small></td>${isAdmin()?`<td>${esc(b.profiles?.name||'User')}<small>${esc(b.profiles?.role||'')}</small></td>`:''}<td>${fmtDate(b.booking_date)}<small>${esc(b.start_time.slice(0,5))}–${esc(b.end_time.slice(0,5))}</small></td><td><span class="status ${b.status}">${statusLabel(b.status)}</span></td><td><button data-detail="${b.id}">View details</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty"><p>No records yet.</p></div>`}`);document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.bookingFilter=b.dataset.filter;bookings()});document.querySelector('#bookingSearch').oninput=e=>{state.search=e.target.value;bookings()};document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>bookingDetails(state.bookings.find(x=>x.id===b.dataset.detail)))}
function bookingDetails(b){if(!b)return;modal('Booking details',`<div class="details"><div><span>Requester</span><strong>${esc(b.profiles?.name||'User')}</strong></div><div><span>Room</span><strong>${esc(b.rooms?.name||'Room')}</strong></div><div><span>Participants</span><strong>${b.participants}</strong></div><div><span>Date</span><strong>${fmtDate(b.booking_date)}</strong></div><div><span>Time</span><strong>${esc(b.start_time.slice(0,5))}–${esc(b.end_time.slice(0,5))}</strong></div><div><span>Purpose</span><strong>${esc(b.purpose)}</strong></div><div><span>Status</span><strong>${statusLabel(b.status)}</strong></div><div><span>Submitted</span><strong>${fmtDT(b.created_at)}</strong></div></div><div class="modal-actions">${isAdmin()&&b.status==='pending'?`<button class="danger" data-status="rejected">Reject</button><button class="primary" data-status="approved">Approve</button>`:''}${!isAdmin()&&can('manage_own_bookings')&&b.user_id===state.user.id&&b.status==='pending'?'<button class="danger" data-status="cancelled">Cancel request</button>':''}</div>`);document.querySelectorAll('[data-status]').forEach(btn=>btn.onclick=async()=>{const{error}=await supabase.from('bookings').update({status:btn.dataset.status}).eq('id',b.id);if(error)return fail(error);await loadData();closeModal();bookings()})}

function calendar(){if(!can('calendar')){setPage('<div class="empty"><p>Calendar access is disabled for your account.</p></div>');return}setPage(`<div class="toolbar"><div><h3>Calendar</h3><p>Your private events + published events</p></div><button class="primary" id="addEvent">+ Add calendar event</button></div>${state.events.length?`<div class="event-list">${state.events.map(e=>`<div class="event-card"><div class="event-date"><strong>${new Date(`${e.event_date}T00:00:00`).getDate()}</strong><span>${new Date(`${e.event_date}T00:00:00`).toLocaleString(undefined,{month:'short'})}</span></div><div><h3>${esc(e.title)}</h3><p>${esc(e.profiles?.name||'')} ${e.event_time?`· ${esc(e.event_time.slice(0,5))}`:''}</p></div><span class="status ${e.published?'approved':'cancelled'}">${e.published?'Published':'Private'}</span></div>`).join('')}</div>`:`<div class="empty"><p>No events yet.</p></div>`}`);document.querySelector('#addEvent').onclick=eventModal}
function eventModal(){if(!can('calendar'))return;modal('Add calendar event',`<form id="eventForm"><label>Event title<input name="title" required></label><div class="two"><label>Date<input name="date" type="date" required></label><label>Time<input name="time" type="time"></label></div><label class="check"><input name="published" type="checkbox"><span>Publish / Notify Everyone</span></label><button class="primary full">Save event</button></form>`);document.querySelector('#eventForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),{error}=await supabase.from('events').insert({user_id:state.user.id,title:String(fd.get('title')).trim(),event_date:String(fd.get('date')),event_time:String(fd.get('time'))||null,published:fd.has('published')});if(error)return fail(error);await loadData();closeModal();calendar()}}

function notifications(){if(!can('notifications')){setPage('<div class="empty"><p>Notifications are disabled for your account.</p></div>');return}setPage(`<div class="notif-toolbar"><span>${state.notifications.filter(n=>!n.read).length} unread</span>${state.notifications.some(n=>!n.read)?'<button id="markAll">Mark all as read</button>':''}</div>${state.notifications.length?`<div class="notice-list">${state.notifications.map(n=>`<div class="notice ${n.read?'':'unread'}"><div class="notice-dot"></div><div class="notice-content"><p>${esc(n.message)}</p><small>${fmtDT(n.created_at)}</small></div>${!n.read?`<button data-read="${n.id}">Mark read</button>`:''}</div>`).join('')}</div>`:`<div class="empty"><p>No notifications yet.</p></div>`}`);document.querySelector('#markAll')?.addEventListener('click',async()=>{const{error}=await supabase.from('notifications').update({read:true}).eq('user_id',state.user.id);if(error)return fail(error);await loadData();notifications()});document.querySelectorAll('[data-read]').forEach(b=>b.onclick=async()=>{await supabase.from('notifications').update({read:true}).eq('id',b.dataset.read);await loadData();notifications()})}

function profile(){if(!can('profile')){setPage('<div class="empty"><p>Profile management is disabled for your account.</p></div>');return}const p=state.profile;setPage(`<div class="profile-layout"><div class="panel profile-summary"><div class="avatar profile-avatar">${esc((p?.name||'U')[0].toUpperCase())}</div><h3>${esc(p?.name||'')}</h3><p>${esc(p?.email||state.user.email)}</p><span class="role-pill">${esc(p?.role||'')}</span></div><div class="panel"><h3>Edit profile</h3><form id="profileForm"><div class="two"><label>Full name<input name="name" value="${esc(p?.name||'')}" required></label><label>Email<input value="${esc(p?.email||state.user.email)}" disabled></label></div><div class="two"><label>ID number<input name="id_number" value="${esc(p?.id_number||'')}"></label><label>Phone number<input name="phone" value="${esc(p?.phone||'')}"></label></div><label>Department / Section<input name="department" value="${esc(p?.department||'')}"></label><button class="primary">Save profile</button></form></div></div>`);document.querySelector('#profileForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),{error}=await supabase.from('profiles').update({name:String(fd.get('name')).trim(),id_number:String(fd.get('id_number')||'').trim(),phone:String(fd.get('phone')||'').trim(),department:String(fd.get('department')||'').trim()}).eq('id',state.user.id);if(error)return fail(error);await loadData();profile()}}

function bindUiCustomizer(){
 document.querySelector('#uiTheme')?.addEventListener('change',e=>{saveUiPrefs({theme:e.target.value});renderApp()});
 document.querySelector('#uiFont')?.addEventListener('change',e=>{saveUiPrefs({fontSize:e.target.value});document.querySelector('#uiSaved').textContent='Font size updated.'});
 document.querySelector('#uiDensity')?.addEventListener('change',e=>{saveUiPrefs({density:e.target.value});document.querySelector('#uiSaved').textContent='Layout density updated.';renderApp()});
 document.querySelector('#uiDesign')?.addEventListener('change',e=>{saveUiPrefs({design:e.target.value});document.querySelector('#uiSaved').textContent='Design style updated.';renderApp()});
}


function settings(){
 const s=state.settings||{},days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],b=brand();
 const p=uiPrefs();
 const uiPanel=`<div class="panel ui-customizer"><div class="section-heading"><div><h3>Customize my interface</h3><p class="muted-copy">These preferences are personal to this account/device and apply immediately.</p></div></div><div class="custom-grid"><label>Theme<select id="uiTheme"><option value="light" ${p.theme==='light'?'selected':''}>Light</option><option value="dark" ${p.theme==='dark'?'selected':''}>Dark</option><option value="system" ${p.theme==='system'?'selected':''}>Follow device</option></select></label><label>Font size<select id="uiFont"><option value="small" ${p.fontSize==='small'?'selected':''}>Small</option><option value="default" ${p.fontSize==='default'?'selected':''}>Default</option><option value="large" ${p.fontSize==='large'?'selected':''}>Large</option><option value="xl" ${p.fontSize==='xl'?'selected':''}>Extra large</option></select></label><label>Layout density<select id="uiDensity"><option value="compact" ${p.density==='compact'?'selected':''}>Compact</option><option value="comfortable" ${p.density==='comfortable'?'selected':''}>Comfortable</option><option value="spacious" ${p.density==='spacious'?'selected':''}>Spacious</option></select></label><label>Design style<select id="uiDesign"><option value="modern" ${p.design==='modern'?'selected':''}>Modern</option><option value="soft" ${p.design==='soft'?'selected':''}>Soft cards</option><option value="minimal" ${p.design==='minimal'?'selected':''}>Minimal</option></select></label></div><div id="uiSaved" class="muted-copy"></div></div>`;
 if(!isAdmin()){
  setPage(`${uiPanel}<div class="panel"><h3>System settings</h3><p class="muted-copy">Branding, rooms, school hours, permissions, and other shared settings are managed by the administrator and sync automatically.</p></div>`);
  bindUiCustomizer();return;
 }
 const perms=s.permissions||defaultPermissions;
 const permissionLabels=[['view_rooms','View rooms / facilities'],['book_rooms','Book rooms'],['manage_own_bookings','Manage own bookings'],['calendar','Use calendar'],['profile','Edit own profile'],['notifications','Use notifications']];
 setPage(`<div class="settings-grid"><div class="panel"><h3>System branding</h3><p class="muted-copy">Changes are stored in Supabase and sync to every signed-in user.</p><form id="brandForm"><label>System name<input name="app_name" value="${esc(b.name)}" required></label><label>Tagline<input name="tagline" value="${esc(b.tagline)}"></label><label>Logo<input name="logo" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml"></label>${b.logo?`<img class="room-form-preview" src="${esc(b.logo)}" alt="Current logo">`:''}<div id="brandMsg"></div><button class="primary full">Save branding</button></form></div><div class="panel"><h3>School hours</h3><form id="settingsForm"><label>Open days<div class="days">${days.map((d,i)=>`<button type="button" data-day="${i}" class="${(s.open_days||[]).includes(i)?'active':''}">${d}</button>`).join('')}</div></label><div class="two"><label>Opening<input name="open" type="time" value="${(s.open_time||'07:00').slice(0,5)}"></label><label>Closing<input name="close" type="time" value="${(s.close_time||'18:00').slice(0,5)}"></label></div><button class="primary">Save school hours</button></form></div><div class="panel" style="grid-column:1/-1"><h3>Teacher & Student permissions</h3><p class="muted-copy">Toggle exactly what each role can use. Admin always keeps full control.</p><div class="permission-grid">${['teacher','student'].map(role=>`<div class="permission-role"><h4>${role[0].toUpperCase()+role.slice(1)}</h4>${permissionLabels.map(([key,label])=>`<label class="permission-check"><input type="checkbox" data-role="${role}" data-perm="${key}" ${perms[role]?.[key]?'checked':''}><span>${label}</span></label>`).join('')}</div>`).join('')}</div><button class="primary" id="savePermissions">Save permissions</button><div id="permMsg"></div></div></div>` + uiPanel);
 bindUiCustomizer();
 let openDays=[...(s.open_days||[1,2,3,4,5])];
 document.querySelectorAll('[data-day]').forEach(x=>x.onclick=()=>{const d=Number(x.dataset.day);openDays=openDays.includes(d)?openDays.filter(v=>v!==d):[...openDays,d].sort();x.classList.toggle('active')});
 document.querySelector('#settingsForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),open=String(fd.get('open')),close=String(fd.get('close'));if(!openDays.length)return alert('Select at least one open day.');if(open>=close)return alert('Closing time must be later than opening time.');const{error}=await supabase.from('app_settings').update({open_days:openDays,open_time:open,close_time:close,updated_at:new Date().toISOString()}).eq('id',1);if(error)return fail(error);await loadData();settings()};
 document.querySelector('#brandForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),msg=document.querySelector('#brandMsg');try{let logo_url=b.logo;const file=fd.get('logo');if(file?.size){if(file.size>3*1024*1024)throw new Error('Logo must be 3 MB or smaller.');const ext=file.name.split('.').pop().toLowerCase();const filePath=`branding/logo-${Date.now()}.${ext}`;const{error:upErr}=await supabase.storage.from('site-assets').upload(filePath,file,{upsert:true,contentType:file.type});if(upErr)throw upErr;logo_url=supabase.storage.from('site-assets').getPublicUrl(filePath).data.publicUrl}const{error}=await supabase.from('app_settings').update({app_name:String(fd.get('app_name')).trim(),tagline:String(fd.get('tagline')||'').trim(),logo_url,updated_at:new Date().toISOString()}).eq('id',1);if(error)throw error;await loadData();settings()}catch(err){msg.innerHTML=`<div class="alert error">${esc(err.message)}</div>`}};
 document.querySelector('#savePermissions').onclick=async()=>{const next=JSON.parse(JSON.stringify(perms));for(const input of document.querySelectorAll('[data-role][data-perm]')){next[input.dataset.role]=next[input.dataset.role]||{};next[input.dataset.role][input.dataset.perm]=input.checked}const{error}=await supabase.from('app_settings').update({permissions:next,updated_at:new Date().toISOString()}).eq('id',1);if(error)return fail(error);await loadData();settings()};
}

async function users(){
 if(!isAdmin()){setPage('<div class="empty"><p>Admin access only.</p></div>');return}
 const{data,error}=await supabase.from('profiles').select('*').order('name');if(error)return fail(error);
 setPage(`<div class="toolbar"><p>Manage users and roles. Public signup can create Student or Teacher accounts only.</p></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Department</th><th></th></tr></thead><tbody>${(data||[]).map(u=>`<tr><td><strong>${esc(u.name||'—')}</strong></td><td>${esc(u.email||'—')}</td><td><select data-user-role="${u.id}"><option value="student" ${u.role==='student'?'selected':''}>Student</option><option value="teacher" ${u.role==='teacher'?'selected':''}>Teacher</option><option value="admin" ${u.role==='admin'?'selected':''}>Admin</option></select></td><td>${esc(u.department||'—')}</td><td><button data-save-user="${u.id}">Save</button></td></tr>`).join('')}</tbody></table></div>`);
 document.querySelectorAll('[data-save-user]').forEach(btn=>btn.onclick=async()=>{const id=btn.dataset.saveUser,role=document.querySelector(`[data-user-role="${id}"]`).value;const{error}=await supabase.from('profiles').update({role}).eq('id',id);if(error)return fail(error);await loadData();users()});
}

boot().catch(err=>{console.error(err);root.innerHTML=`<div class="auth-page"><div class="auth-card"><div class="alert error">${esc(err.message)}</div></div></div>`});
